import "./globals.css";
import Navigation from "./components/layout/navigation";
import Footer from "./components/layout/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
