import "./globals.css";

import Navigation from "./components/layout/navigation";
import Footer from "./components/layout/footer";
import { DarkModeProvider } from "@/app/components/component/useDarkMode";

export const metadata = {
  icons: {
    icon: "/image/Logo.png", // Place logo in /public folder
  },
  title: "xBot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={``}>
      <body className={`antialiased bg-white dark:bg-bg`}>
        <DarkModeProvider>
          <Navigation />
          {children}
          <Footer />
        </DarkModeProvider>
      </body>
    </html>
  );
}
